services:
  db:
    image: postgres:15-alpine
    container_name: erp_postgres
    restart: always
    environment:
      POSTGRES_USER: johan_admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: erp_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: